name: Deploy SAM Lambda

on:
  push:
    branches:
      - master  # deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # 3️⃣ Install AWS CLI and SAM CLI
    - name: Install AWS CLI and SAM CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
        pip install --upgrade pip
        pip install aws-sam-cli
        sam --version

    # 4️⃣ Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 5️⃣ Build the SAM application
    - name: Build SAM application
      run: sam build

    # 6️⃣ Deploy the SAM application
    - name: Deploy SAM application
      run: |
        sam deploy --stack-name sam-python-crud-sample \
                   --capabilities CAPABILITY_IAM \
                   --resolve-s3
